Pass size_bytes from crate_download to ctx.actions.download_file
    Error running analysis for `rust//stage1:rustc (null#b3d32bdae3fc2480)`

    Caused by:
        0: Error in configured node dependency, dependency chain follows (-> indicates depends on, ^ indicates same configuration as previous):
                  rust//stage1:rustc (null#b3d32bdae3fc2480)
               -> rust//stage1:rustc (rust//platforms/stage1:compiler#e891cf7160cb85c2)
               -> rust//stage0:ci_llvm (^)
               -> rust//stage0:ci_llvm (rust//platforms:host#6c8c3836670f2453)
               -> rust//stage0:rust_dev (^)
               -> rust//:stage0_manifest (^)

        1: looking up unconfigured target node `rust//:stage0_manifest`
        2: Error loading targets in package `rust//` for target `rust//:stage0_manifest`
        3: Error evaluating build file: `rust//:BUCK`
        4: Traceback (most recent call last):
             * BUCK:29, in <module>
                 crate_download(
             * crates.io/crate_download.bzl:4, in crate_download
                 _crate_download(
           error: Found `size_bytes` extra named parameter(s) for call to crate_download
            --> crates.io/crate_download.bzl:4:5
             |
           4 | /     _crate_download(
           5 | |         incoming_transition = "//crates.io:download",
           6 | |         **kwargs
           7 | |     )
             | |_____^