Add CxxToolchainInfo.bolt_enabled
    BUILD FAILED
    Error running analysis for `rust//stage2:test (null#b3d32bdae3fc2480)`

    Caused by:
        0: Error running analysis for `rust//stage2:test (rust//platforms/stage2:library#40c2c33f1d0083db)`
        1: Error running analysis for `rust//:test (rust//platforms/stage2:library#40c2c33f1d0083db)`
        2: Error running analysis for `toolchains//:rust (rust//platforms/stage2:library#40c2c33f1d0083db) (rust//platforms/stage2:library-build-script#085660500511562b)`
        3: Error running analysis for `rust//stage2:rustc (rust//platforms/stage2:library-build-script#085660500511562b)`
        4: Error running analysis for `rust//stage2:rustc (rust//platforms/stage2:compiler#6d13ade175a709a5)`
        5: Error running analysis for `rust//:rustc-main-rustc-main (rust//platforms/stage2:compiler#6d13ade175a709a5)`
        6: Error running analysis for `rust//:rustc-main-0.0.0-rustc-main (rust//platforms/stage2:compiler#6d13ade175a709a5)`
        7: Error running analysis for `rust//:_rustc_index_macros (rust//platforms/stage2:compiler-build-script#47d66f721435564f)`
        8: Error running analysis for `rust//:proc-macro2-1 (rust//platforms/stage2:compiler-build-script#47d66f721435564f)`
        9: Error running analysis for `rust//:proc-macro2-1-build-script-run (rust//platforms/stage2:compiler-build-script#47d66f721435564f)`
       10: Error running analysis for `rust//:proc-macro2-1-build-script-build-linux-x86_64-compiler (rust//platforms/stage2:compiler-build-script#47d66f721435564f)`
       11: Error running analysis for `rust//:proc-macro2-1-build-script-build-linux-x86_64-compiler (rust//platforms/stage2:compiler-build-script#628e552c3bc78547)`
       12: Error running analysis for `rust//:proc-macro2-1-build-script-build (rust//platforms/stage2:compiler-build-script#628e552c3bc78547)`
       13: Traceback (most recent call last):
             File <builtin>, in <module>
             * prelude/rust/rust_binary.bzl:701, in rust_binary_impl
                 providers, args = _rust_binary_common(
             * prelude/rust/rust_binary.bzl:361, in _rust_binary_common
                 link = rust_compile(
             * prelude/rust/build.bzl:891, in rust_compile
                 cxx_link_result = _rust_cxx_link(
             * prelude/rust/build.bzl:590, in _rust_cxx_link
                 return cxx_link_into(
             * prelude/cxx/link.bzl:479, in cxx_link_into
                 use_bolt = is_result_executable and cxx_use_bolt(ctx)
           error: Value `None` of type `NoneType` does not match the type annotation `bool` for return type
             --> prelude/cxx/cxx_bolt.bzl:26:5
              |
           26 |     return cxx_toolchain_info.bolt_enabled and ctx.attrs.bolt_profile != None
              |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              |