Set RUSTC_BOOTSTRAP for stage0 print=cfg invocation
Required since https://github.com/facebook/buck2/commit/ebfa7aadb1653e1a2080e458e2efa3c734594fd6

    Action failed: prelude//rust/tools:rustc_cfg (rustc_cfg)
    error: the option `Z` is only accepted on the nightly compiler

    help: consider switching to a nightly toolchain: `rustup default nightly`

    note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

    note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

    error: 1 nightly option were parsed

    BUILD FAILED
    Failed to build 'prelude//rust/tools:rustc_cfg (rust//platforms/stage1:compiler-build-script#7dc0249531bb3268)'