Move -Clink-arg to linker_flags
    Error running analysis for `rust//stage2:rustc (null#b3d32bdae3fc2480)`

    Caused by:
        0: Error running analysis for `rust//stage2:rustc (rust//platforms/stage2:compiler#b15ea5ec21b2ad47)`
        1: Error running analysis for `rust//:rustc-main-rustc-main (rust//platforms/stage2:compiler#b15ea5ec21b2ad47)`
        2: Error running analysis for `rust//:rustc-main-0.0.0-rustc-main (rust//platforms/stage2:compiler#b15ea5ec21b2ad47)`
        3: Error running analysis for `rust//:_yoke-derive-0.8 (rust//platforms/stage2:compiler-build-script#52fc988b7e869f7d)`
        4: Error running analysis for `toolchains//:rust (rust//platforms/stage2:compiler-build-script#52fc988b7e869f7d) (rust//platforms/stage2:compiler-build-script#52fc988b7e869f7d)`
        5: Error running analysis for `rust//stage1:core (rust//platforms/stage2:compiler-build-script#52fc988b7e869f7d)`
        6: Error running analysis for `rust//stage1:core (rust//platforms/stage1:library#82b53c80451dc3c1)`
        7: Error running analysis for `rust//:core (rust//platforms/stage1:library#82b53c80451dc3c1)`
        8: Traceback (most recent call last):
             File <builtin>, in <module>
             * prelude/rust/rust_library.bzl:170, in rust_library_impl
                 meta_fast = rust_compile(
             * prelude/rust/build.bzl:462, in rust_compile
                 common_args = _compute_common_args(
             * prelude/rust/build.bzl:1226, in _compute_common_args
                 _rustc_flags(toolchain_info.rustc_flags, toolchain_info),
             * prelude/rust/build.bzl:962, in _rustc_flags
                 fail("-Clink-arg is not supported with advanced_unstable_linking, use the " +
           error: fail: -Clink-arg is not supported with advanced_unstable_linking, use the target's or toolchain's `linker_flags` instead
              --> prelude/rust/build.bzl:962:17
               |
           962 |                   fail("-Clink-arg is not supported with advanced_unstable_linking, use the " +
               |  _________________^
           963 | |                      "target's or toolchain's `linker_flags` instead")
               | |______________________________________________________________________^
               |