Fix explicit sysroot deps for sysroot dep collection
    Error running analysis for `rust//stage1:sysroot (null#abcbb4ae6698b615)`

    Caused by:
        0: Error running analysis for `rust//stage1:sysroot (rust//platforms/stage1:library#fb625d5f8bb8b2d9)`
        1: Traceback (most recent call last):
             File <builtin>, in <module>
             * stage1/defs.bzl:75, in _sysroot_impl
                 deps = resolve_deps(ctx = ctx, dep_ctx = dep_ctx)
             * prelude/rust/link_info.bzl:386, in resolve_deps
                 return dependencies + gather_explicit_sysroot_deps(dep_ctx)
             * prelude/rust/link_info.bzl:320, in gather_explicit_sysroot_deps
                 fail("Explicit sysroot deps are required when advanced_unstable_linking is on")
           error: fail: Explicit sysroot deps are required when advanced_unstable_linking is on
              --> prelude/rust/link_info.bzl:320:13
               |
           320 |             fail("Explicit sysroot deps are required when advanced_unstable_linking is on")
               |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               |